# Generated by Django 3.0.5 on 2020-07-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
        ('blog', '0005_auto_20200411_1418'),
        ('blog', '0003_auto_20200410_1559'),
    ]

    operations = [
    ]
